#!/bin/bash

echo "Starting..."

# write creds to file
cat <<EOF > /opt/aws.creds
export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
EOF

# workaround for too many hardlinks
touch /etc/crontab /etc/cron.* /etc/cron.*/* /var/spool/cron /var/spool/cron/crontabs /opt/*

echo "Replacing process with cron..."
exec cron -f
