---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kops-etcd-backups
  namespace: kube-system
...
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kops-etcd-backups
  namespace: kube-system
  labels:
    app: kops-etcd-backups
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
  selector:
    matchLabels:
      name: kops-etcd-backups
  template:
    metadata:
      labels:
        name: kops-etcd-backups
    spec:
      serviceAccount: kops-etcd-backups
      terminationGracePeriodSeconds: 5
      nodeSelector:
        kubernetes.io/role: master
      tolerations:
      - operator: "Exists"
      containers:
      - name: kops-etcd-backups
        image: missioncriticalkubernetes/kops-etcd-backups:1.0.1
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: kops-etcd-backups
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: kops-etcd-backups
              key: AWS_SECRET_ACCESS_KEY
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
...
